version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
build_script:
- pwsh: >-
    dotnet build --configuration Debug
    
    dotnet build --configuration Release
    
    dotnet test
    
    dotnet publish -c release -o .\bin\publish\all\
    
    Remove-Item *.pdb
artifacts:
- path: bin\publish\all
  name: HeroesDataParser-FDD-All
  type: zip