image: Visual Studio 2017
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
build_script:
- pwsh: >-
    dotnet build --configuration Debug
    
    dotnet build --configuration Release
    
    dotnet test
    
    dotnet publish -c release -o .\bin\publish\all\
    
    Remove-Item .\HeroesData\bin\publish\all\*.pdb
artifacts:
- path: '.\HeroesData\bin\publish\all'
  name: HeroesDataParser-FDD-All
  type: zip
deploy:
  release: Heroes Data Parser
  description: '## What''s New\n## Fixes\n## Other\n## Builds'
  provider: GitHub
  auth_token:
    secure: qr/xMva47Xz8Ea9FcoYTUEFG72wxhgFTINZW8emNDlkWmopOH1ZK9BD3k+8LMsdU
  artifact: HeroesData\bin\publish\HeroesDataParser-FDD-All.zip
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true