version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: dotnet build
build:
  parallel: true
  verbosity: minimal
